# Generated by Django 5.2.4 on 2026-09-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproposal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
