# Generated by Django 5.2.4 on 2026-09-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('service', 'Service')], max_length=20, null=True),
        ),
    ]
