# Generated by Django 5.2.4 on 2026-09-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_proposal', 'New Proposal'), ('price_updated', 'Price Updated'), ('proposal_approved', 'Proposal Approved'), ('project_completed', 'Project Completed'), ('new_rating', 'New Rating')], max_length=30),
        ),
    ]
