# Generated by Django 5.2.4 on 2025-07-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_rating', '0001_initial'),
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrating',
            name='freelancer',
            field=models.ForeignKey(help_text='The freelancer being rated.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='freelancer.freelancer'),
        ),
    ]
