# Generated by Django 5.2.4 on 2025-07-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_rating', '0002_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrating',
            name='project',
            field=models.ForeignKey(help_text='The project associated with the rating.', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='project.project'),
        ),
    ]
